package com.warlordjones.steampunkery.tileentities.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

//Model code generated by MCModeller. All animation, AI,
//and special features are yours to program. Also keep in
//mind that some of these class names may have changed since
//wrote this. Make sure to check for compatibility with the
//latest version of the Minecraft Coder Pack before attempting
//to use this code.

public class ModelConveyor extends ModelBase {
    public ModelRenderer bottom;
    public ModelRenderer end;
    public ModelRenderer end1;
    public ModelRenderer roller;
    public ModelRenderer roller1;
    public ModelRenderer roller2;
    public ModelRenderer top;

    public ModelConveyor() {
	top = new ModelRenderer(this, 0, 0);
	top.addBox(-8.0F, -4.5F, -7.0F, 16, 1, 14, 0);

	bottom = new ModelRenderer(this, 0, 0);
	bottom.addBox(-8.0F, -0.5F, -7.0F, 16, 1, 14, 0);

	end = new ModelRenderer(this, 0, 0);
	end.addBox(8.0F, -4.0F, -7.0F, 1, 4, 14, 0);

	end1 = new ModelRenderer(this, 0, 0);
	end1.addBox(-9.0F, -4.0F, -7.0F, 1, 4, 14, 0);

	roller = new ModelRenderer(this, 0, 0);
	roller.addBox(3.5F, -3.5F, -6.5F, 3, 3, 13, 0);

	roller1 = new ModelRenderer(this, 0, 0);
	roller1.addBox(-1.5F, -3.5F, -6.5F, 3, 3, 13, 0);

	roller2 = new ModelRenderer(this, 0, 0);
	roller2.addBox(-6.5F, -3.5F, -6.5F, 3, 3, 13, 0);

    }

    public void render(final float f, final float f1, final float f2,
	    final float f3, final float f4, final float f5) {
	this.setRotationAngles(f, f1, f2, f3, f4, f5);
	top.render(f5);
	bottom.render(f5);
	end.render(f5);
	end1.render(f5);
	roller.render(f5);
	roller1.render(f5);
	roller2.render(f5);
    }

    // Method you're going to want to override:
    public void setRotationAngles(final float f, final float f1,
	    final float f2, final float f3, final float f4, final float f5) {
    }

}
