/*
 * @author warlordjones
 * 
 * Using this source for addon development or examples/education is cool with me. 
 * Taking this source code and claiming it is yours isn't cool!

 */
package com.warlordjones.steampunkery.tileentities.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

//Model code generated by MCModeller. All animation, AI,
//and special features are yours to program. Also keep in
//mind that some of these class names may have changed since
//wrote this. Make sure to check for compatibility with the
//latest version of the Minecraft Coder Pack before attempting
//to use this code.

//Model code generated by MCModeller. All animation, AI,
//and special features are yours to program. Also keep in
//mind that some of these class names may have changed since
//wrote this. Make sure to check for compatibility with the
//latest version of the Minecraft Coder Pack before attempting
//to use this code.

public class ModelIBeam extends ModelBase {
    public ModelRenderer beam_center;
    public ModelRenderer beam_side;
    public ModelRenderer beam_side2;

    public ModelIBeam() {
	beam_center = new ModelRenderer(this, 0, 0);
	beam_center.addBox(-1.5F, 11.5F, -8.0F, 3, 9, 16, 0);

	beam_side = new ModelRenderer(this, 0, 0);
	beam_side.addBox(-8.0F, 8.5F, -8.0F, 16, 3, 16, 0);

	beam_side2 = new ModelRenderer(this, 0, 0);
	beam_side2.addBox(-8.0F, 20.5F, -8.0F, 16, 3, 16, 0);

    }

    public void render(final float f, final float f1, final float f2,
	    final float f3, final float f4, final float f5) {
	this.setRotationAngles(f, f1, f2, f3, f4, f5);
	beam_center.render(f5);
	beam_side.render(f5);
	beam_side2.render(f5);
    }

    // Method
    public void renderModel(final float f, final float f1, final float f2,
	    final float f3, final float f4, final float f5) {
	this.setRotationAngles(f, f1, f2, f3, f4, f5);
	beam_center.render(f5);
	beam_side.render(f5);
	beam_side2.render(f5);
    }

    public void setRotationAngles(final float f, final float f1,
	    final float f2, final float f3, final float f4, final float f5) {
    }

}
